-- ============================================================================
--  Importa 30 ejercicios guided_steps de Certamen 2 desde JSON validado.
--  Fuente original: /home/ftt-2brocket/github/PIEGI/material-estadistica-aplicada/30-ejercicios-certamen2-guided-steps.json
-- ============================================================================

insert into public.courses
  (id, title, subtitle, description, emoji, sort_order, is_published)
values (
  'estadistica-aplicada',
  'Estadistica Aplicada',
  'COP321 - USM',
  'Ejercicios guiados de probabilidad para Certamen 2.',
  '📊',
  20,
  true
)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  emoji = excluded.emoji,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;

insert into public.course_modules
  (id, course_id, title, emoji, intro, theory, sort_order, is_published, media)
values (
  'estadistica-certamen2-probabilidad',
  'estadistica-aplicada',
  'Certamen 2 - Probabilidad',
  '🎲',
  'Practica guiada de conteo, probabilidad clasica, condicional, independencia, probabilidad total y Bayes.',
  '<p>Resuelve cada ejercicio paso a paso. Avanza cuando el calculo y la interpretacion esten claros.</p>',
  20,
  true,
  '{}'::jsonb
)
on conflict (id) do update set
  course_id = excluded.course_id,
  title = excluded.title,
  emoji = excluded.emoji,
  intro = excluded.intro,
  theory = excluded.theory,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;

insert into public.course_items
  (id, course_id, module_id, type, title, level, statement_html, hint, starter, tests, options, correct_answer, explanation, solution_html, steps, sort_order, is_published)
values
  ('est-c2-gs-001', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Codigo con letras y digitos', 1, '<p>Un codigo se forma con 2 letras distintas tomadas de A, B, C, D, E y luego 2 digitos de 0 a 9, con repeticion permitida. Calcula cuantos codigos hay.</p>', 'Usa el principio multiplicativo.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"info","title":"Identifica las opciones","content_html":"<p>Primera letra: 5 opciones. Segunda letra: 4 opciones. Cada digito: 10 opciones.</p>"},{"kind":"formula","title":"Plantea el conteo","prompt":"Escribe el producto que cuenta los codigos.","accepted":["5*4*10*10","5 x 4 x 10 x 10","5·4·10·10"],"hint":"Multiplica las opciones de cada posicion.","explanation":"El codigo tiene cuatro posiciones independientes: letra, letra, digito, digito."},{"kind":"numeric","title":"Calcula el total","prompt":"Ingresa el numero total de codigos.","answer":2000,"tolerance":0,"hint":"5*4*10*10.","explanation":"5*4*10*10 = 2000."}]'::jsonb, 10, true),
  ('est-c2-gs-002', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Directiva y comision', 1, '<p>De 9 personas se debe formar una directiva con presidente, secretario y tesorero, y tambien una comision de 3 personas sin cargos.</p>', 'Distingue si importa o no importa el orden.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"single","title":"Directiva","prompt":"Para presidente, secretario y tesorero, que tecnica corresponde?","options":[{"id":"a","label":"Permutaciones"},{"id":"b","label":"Combinaciones"}],"answer":"a","hint":"Los cargos son distintos.","explanation":"Como los cargos cambian el resultado, importa el orden."},{"kind":"numeric","title":"Calcula la directiva","prompt":"Cuantas directivas distintas hay?","answer":504,"tolerance":0,"hint":"P(9,3)=9*8*7.","explanation":"P(9,3)=9*8*7=504."},{"kind":"numeric","title":"Calcula la comision","prompt":"Cuantas comisiones de 3 personas sin cargos hay?","answer":84,"tolerance":0,"hint":"C(9,3).","explanation":"C(9,3)=9!/(3!*6!)=84."}]'::jsonb, 20, true),
  ('est-c2-gs-003', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Comision con al menos una mujer', 2, '<p>En un grupo hay 7 hombres y 5 mujeres. Se elige una comision de 4 personas. Cuantas comisiones tienen al menos una mujer?</p>', 'Usa complemento: total menos comisiones sin mujeres.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Total de comisiones","prompt":"Calcula C(12,4).","answer":495,"tolerance":0,"hint":"Hay 12 personas en total.","explanation":"C(12,4)=495."},{"kind":"numeric","title":"Comisiones sin mujeres","prompt":"Calcula las comisiones formadas solo por hombres.","answer":35,"tolerance":0,"hint":"C(7,4).","explanation":"C(7,4)=35."},{"kind":"numeric","title":"Al menos una mujer","prompt":"Calcula el resultado final.","answer":460,"tolerance":0,"hint":"Resta 495 - 35.","explanation":"Al menos una mujer = 495 - 35 = 460."}]'::jsonb, 30, true),
  ('est-c2-gs-004', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Suma 9 con dos dados', 1, '<p>Se lanzan dos dados equilibrados. Calcula P(suma 9).</p>', 'Enumera los pares ordenados que suman 9.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Espacio muestral","prompt":"Cuantos resultados posibles hay al lanzar dos dados?","answer":36,"tolerance":0,"hint":"6 opciones para cada dado.","explanation":"6*6=36 pares ordenados."},{"kind":"numeric","title":"Casos favorables","prompt":"Cuantos pares suman 9?","answer":4,"tolerance":0,"hint":"(3,6), (4,5), (5,4), (6,3).","explanation":"Hay 4 casos favorables."},{"kind":"numeric","title":"Probabilidad","prompt":"Ingresa P(suma 9) como decimal.","answer":0.111111,"tolerance":0.001,"hint":"4/36.","explanation":"P(suma 9)=4/36=1/9=0,1111."}]'::jsonb, 40, true),
  ('est-c2-gs-005', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Suma 7 o suma 8', 1, '<p>Se lanzan dos dados. Calcula P(suma 7 o suma 8).</p>', 'Los eventos son mutuamente excluyentes.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Casos suma 7","prompt":"Cuantos casos suman 7?","answer":6,"tolerance":0,"hint":"Parte desde (1,6).","explanation":"Suma 7 tiene 6 casos."},{"kind":"numeric","title":"Casos suma 8","prompt":"Cuantos casos suman 8?","answer":5,"tolerance":0,"hint":"Parte desde (2,6).","explanation":"Suma 8 tiene 5 casos."},{"kind":"numeric","title":"Probabilidad final","prompt":"Ingresa la probabilidad como decimal.","answer":0.305556,"tolerance":0.001,"hint":"(6+5)/36.","explanation":"P=11/36=0,3056."}]'::jsonb, 50, true),
  ('est-c2-gs-006', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Al menos una cara', 1, '<p>Se lanzan 3 monedas. Calcula la probabilidad de obtener al menos una cara.</p>', 'Usa el complemento: ninguna cara.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"single","title":"Metodo conveniente","prompt":"Que evento conviene usar como complemento?","options":[{"id":"a","label":"Ninguna cara"},{"id":"b","label":"Exactamente dos caras"}],"answer":"a","hint":"Al menos una es lo contrario de cero caras.","explanation":"P(al menos una cara)=1-P(ninguna cara)."},{"kind":"numeric","title":"Ninguna cara","prompt":"Calcula P(ninguna cara).","answer":0.125,"tolerance":0.001,"hint":"(1/2)^3.","explanation":"P(ninguna cara)=1/8=0,125."},{"kind":"numeric","title":"Resultado final","prompt":"Calcula P(al menos una cara).","answer":0.875,"tolerance":0.001,"hint":"1 - 0,125.","explanation":"1-1/8=7/8=0,875."}]'::jsonb, 60, true),
  ('est-c2-gs-007', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Exactamente una cara', 1, '<p>Se lanzan 3 monedas. Calcula la probabilidad de obtener exactamente 1 cara.</p>', 'Cuenta las posiciones posibles de la cara.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Casos favorables","prompt":"Cuantos resultados tienen exactamente una cara?","answer":3,"tolerance":0,"hint":"CAA, ACA, AAC.","explanation":"La cara puede estar en cualquiera de las 3 posiciones."},{"kind":"numeric","title":"Casos totales","prompt":"Cuantos resultados posibles hay?","answer":8,"tolerance":0,"hint":"2^3.","explanation":"Tres monedas generan 8 resultados."},{"kind":"numeric","title":"Probabilidad","prompt":"Ingresa la probabilidad como decimal.","answer":0.375,"tolerance":0.001,"hint":"3/8.","explanation":"P=3/8=0,375."}]'::jsonb, 70, true),
  ('est-c2-gs-008', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Figura o corazon', 2, '<p>En una baraja de 52 cartas, A = sacar un corazon y B = sacar una figura. Calcula P(A union B).</p>', 'Usa la formula de union y resta la interseccion.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Corazones","prompt":"Cuantas cartas son corazones?","answer":13,"tolerance":0,"hint":"Una pinta tiene 13 cartas.","explanation":"Hay 13 corazones."},{"kind":"numeric","title":"Figuras","prompt":"Cuantas figuras hay en total?","answer":12,"tolerance":0,"hint":"J, Q, K en 4 pintas.","explanation":"3*4=12 figuras."},{"kind":"numeric","title":"Interseccion","prompt":"Cuantas figuras de corazon hay?","answer":3,"tolerance":0,"hint":"J, Q y K de corazon.","explanation":"La interseccion tiene 3 cartas."},{"kind":"numeric","title":"Union","prompt":"Ingresa P(A union B) como decimal.","answer":0.423077,"tolerance":0.001,"hint":"(13+12-3)/52.","explanation":"P(A union B)=22/52=11/26=0,4231."}]'::jsonb, 80, true),
  ('est-c2-gs-009', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Condicional con baraja', 2, '<p>Con una baraja de 52 cartas, calcula P(reina | carta roja).</p>', 'Al condicionar, el universo se reduce a cartas rojas.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Universo condicionado","prompt":"Cuantas cartas rojas hay?","answer":26,"tolerance":0,"hint":"Corazones + diamantes.","explanation":"Hay 26 cartas rojas."},{"kind":"numeric","title":"Casos favorables","prompt":"Cuantas reinas rojas hay?","answer":2,"tolerance":0,"hint":"Reina de corazon y reina de diamante.","explanation":"Hay 2 reinas rojas."},{"kind":"numeric","title":"Probabilidad condicional","prompt":"Ingresa P(reina | roja) como decimal.","answer":0.076923,"tolerance":0.001,"hint":"2/26.","explanation":"P=2/26=1/13=0,0769."}]'::jsonb, 90, true),
  ('est-c2-gs-010', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Segunda roja dado primera azul', 2, '<p>Una urna tiene 6 rojas y 4 azules. Se extraen 2 sin reposicion. Calcula P(segunda roja | primera azul).</p>', 'Actualiza la urna despues de observar la primera extraccion.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"info","title":"Condicion","content_html":"<p>Ya sabemos que la primera fue azul. Quedan 6 rojas y 3 azules, total 9.</p>"},{"kind":"numeric","title":"Probabilidad condicional","prompt":"Ingresa P(segunda roja | primera azul) como decimal.","answer":0.666667,"tolerance":0.001,"hint":"6/9.","explanation":"P=6/9=2/3=0,6667."},{"kind":"short_text","title":"Interpretacion","prompt":"Explica por que cambio el denominador.","accepted_keywords":["sin reposicion","quedan","9"],"sample_answer":"Como la extraccion es sin reposicion y ya salio una azul, quedan 9 fichas.","hint":"Menciona que no se repone la primera ficha.","explanation":"En extracciones sin reposicion, el total disponible cambia despues de cada extraccion."}]'::jsonb, 100, true),
  ('est-c2-gs-011', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Ambas verdes sin reposicion', 1, '<p>Una caja tiene 5 fichas verdes y 3 amarillas. Se extraen 2 sin reposicion. Calcula P(ambas verdes).</p>', 'Multiplica P(primera verde) por P(segunda verde | primera verde).', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Primera verde","prompt":"Ingresa P(primera verde).","answer":0.625,"tolerance":0.001,"hint":"5/8.","explanation":"P(primera verde)=5/8=0,625."},{"kind":"numeric","title":"Segunda verde","prompt":"Ingresa P(segunda verde | primera verde).","answer":0.571429,"tolerance":0.001,"hint":"4/7.","explanation":"Si ya salio una verde, quedan 4 verdes de 7 fichas."},{"kind":"numeric","title":"Resultado final","prompt":"Ingresa P(ambas verdes).","answer":0.357143,"tolerance":0.001,"hint":"(5/8)(4/7).","explanation":"P=20/56=5/14=0,3571."}]'::jsonb, 110, true),
  ('est-c2-gs-012', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Exactamente una roja', 2, '<p>Una caja tiene 5 rojas y 3 azules. Se extraen 2 sin reposicion. Calcula la probabilidad de obtener exactamente 1 roja.</p>', 'Puede ocurrir roja-azul o azul-roja.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Roja luego azul","prompt":"Calcula P(R luego A).","answer":0.267857,"tolerance":0.001,"hint":"(5/8)(3/7).","explanation":"(5/8)(3/7)=15/56."},{"kind":"numeric","title":"Azul luego roja","prompt":"Calcula P(A luego R).","answer":0.267857,"tolerance":0.001,"hint":"(3/8)(5/7).","explanation":"(3/8)(5/7)=15/56."},{"kind":"numeric","title":"Exactamente una roja","prompt":"Suma ambos casos e ingresa la probabilidad final.","answer":0.535714,"tolerance":0.001,"hint":"15/56 + 15/56.","explanation":"30/56=15/28=0,5357."}]'::jsonb, 120, true),
  ('est-c2-gs-013', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Independencia exacta', 2, '<p>Sean A y B con P(A)=0,4, P(B)=0,5 y P(A inter B)=0,2. Determina si son independientes.</p>', 'Compara P(A inter B) con P(A)P(B).', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Producto","prompt":"Calcula P(A)P(B).","answer":0.2,"tolerance":0.001,"hint":"0,4*0,5.","explanation":"0,4*0,5=0,2."},{"kind":"boolean","title":"Decision","prompt":"A y B son independientes.","answer":true,"hint":"El producto coincide con la interseccion.","explanation":"Como P(A inter B)=P(A)P(B)=0,2, son independientes."}]'::jsonb, 130, true),
  ('est-c2-gs-014', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'No independencia', 2, '<p>Sean A y B con P(A)=0,4, P(B)=0,5 y P(A inter B)=0,18. Determina si son independientes.</p>', 'Independencia exige igualdad exacta entre interseccion y producto.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Producto","prompt":"Calcula P(A)P(B).","answer":0.2,"tolerance":0.001,"hint":"0,4*0,5.","explanation":"0,4*0,5=0,2."},{"kind":"boolean","title":"Decision","prompt":"A y B son independientes.","answer":false,"hint":"Compara 0,18 con 0,20.","explanation":"Como 0,18 es distinto de 0,20, no son independientes."}]'::jsonb, 140, true),
  ('est-c2-gs-015', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Probabilidad total con dos maquinas', 2, '<p>Una fabrica produce piezas con M1: 70% de produccion y 2% defectuosas; M2: 30% de produccion y 5% defectuosas. Calcula P(D).</p>', 'Usa probabilidad total.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"formula","title":"Formula","prompt":"Escribe la formula de P(D) usando M1 y M2.","accepted":["P(D)=P(D|M1)P(M1)+P(D|M2)P(M2)","P(D)=P(M1)P(D|M1)+P(M2)P(D|M2)"],"hint":"Suma el aporte de cada maquina.","explanation":"M1 y M2 forman una particion del origen."},{"kind":"numeric","title":"Aporte M1","prompt":"Calcula P(D|M1)P(M1).","answer":0.014,"tolerance":0.001,"hint":"0,02*0,70.","explanation":"0,02*0,70=0,014."},{"kind":"numeric","title":"Probabilidad total","prompt":"Calcula P(D).","answer":0.029,"tolerance":0.001,"hint":"0,014 + 0,015.","explanation":"P(D)=0,014+0,015=0,029."}]'::jsonb, 150, true),
  ('est-c2-gs-016', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Bayes con dos maquinas', 3, '<p>Con M1: 70% y 2% defectuosas; M2: 30% y 5% defectuosas. Si una pieza salio defectuosa, calcula P(M1 | D). Usa P(D)=0,029.</p>', 'Bayes invierte la condicional.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"single","title":"Formula correcta","prompt":"Cual formula calcula P(M1|D)?","options":[{"id":"a","label":"P(D|M1)P(M1)/P(D)"},{"id":"b","label":"P(M1|D)P(D)/P(M1)"}],"answer":"a","hint":"El numerador junta origen y defecto.","explanation":"P(M1|D)=P(D|M1)P(M1)/P(D)."},{"kind":"numeric","title":"Numerador","prompt":"Calcula P(D|M1)P(M1).","answer":0.014,"tolerance":0.001,"hint":"0,02*0,70.","explanation":"El numerador es 0,014."},{"kind":"numeric","title":"Resultado","prompt":"Calcula P(M1|D).","answer":0.482759,"tolerance":0.001,"hint":"0,014/0,029.","explanation":"P(M1|D)=0,4828."}]'::jsonb, 160, true),
  ('est-c2-gs-017', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Bayes con tres proveedores', 3, '<p>Tres proveedores entregan tornillos: A 50% con 1% de defecto; B 30% con 3%; C 20% con 4%. Si un tornillo sale defectuoso, calcula P(C | D).</p>', 'Primero calcula P(D), luego aplica Bayes.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Probabilidad total","prompt":"Calcula P(D).","answer":0.022,"tolerance":0.001,"hint":"0,01*0,50 + 0,03*0,30 + 0,04*0,20.","explanation":"P(D)=0,005+0,009+0,008=0,022."},{"kind":"numeric","title":"Aporte de C","prompt":"Calcula P(D|C)P(C).","answer":0.008,"tolerance":0.001,"hint":"0,04*0,20.","explanation":"El aporte de C al defecto es 0,008."},{"kind":"numeric","title":"Bayes","prompt":"Calcula P(C|D).","answer":0.363636,"tolerance":0.001,"hint":"0,008/0,022.","explanation":"P(C|D)=0,3636."}]'::jsonb, 170, true),
  ('est-c2-gs-018', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Probabilidad total con tres maquinas', 2, '<p>Una fabrica tiene M1: 50% y 1% de falla; M2: 30% y 3% de falla; M3: 20% y 4% de falla. Calcula P(D).</p>', 'Suma los aportes de cada maquina.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Aporte M1","prompt":"Calcula el aporte de M1.","answer":0.005,"tolerance":0.001,"hint":"0,01*0,50.","explanation":"M1 aporta 0,005."},{"kind":"numeric","title":"Aporte M2","prompt":"Calcula el aporte de M2.","answer":0.009,"tolerance":0.001,"hint":"0,03*0,30.","explanation":"M2 aporta 0,009."},{"kind":"numeric","title":"Probabilidad total","prompt":"Calcula P(D).","answer":0.022,"tolerance":0.001,"hint":"0,005+0,009+0,008.","explanation":"P(D)=0,022."}]'::jsonb, 180, true),
  ('est-c2-gs-019', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Bayes con M2', 3, '<p>Con M1: 50% y 1% de falla; M2: 30% y 3%; M3: 20% y 4%. Si la pieza salio defectuosa, calcula P(M2 | D). Usa P(D)=0,022.</p>', 'El numerador es el aporte de M2 al defecto.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Numerador","prompt":"Calcula P(D|M2)P(M2).","answer":0.009,"tolerance":0.001,"hint":"0,03*0,30.","explanation":"El aporte de M2 es 0,009."},{"kind":"numeric","title":"Bayes","prompt":"Calcula P(M2|D).","answer":0.409091,"tolerance":0.001,"hint":"0,009/0,022.","explanation":"P(M2|D)=0,4091."},{"kind":"short_text","title":"Interpretacion","prompt":"Interpreta el resultado en una frase.","accepted_keywords":["defectuosa","maquina","m2"],"sample_answer":"Si la pieza es defectuosa, hay cerca de 40,9% de probabilidad de que venga de M2.","hint":"Habla desde la condicion: ya se sabe que la pieza es defectuosa.","explanation":"Bayes responde por el origen mas probable dado el defecto observado."}]'::jsonb, 190, true),
  ('est-c2-gs-020', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Combinaciones de estudiantes', 1, '<p>De 12 estudiantes se eligen 4 para una comision sin cargos. Cuantas comisiones distintas hay?</p>', 'Como no hay cargos, usa combinaciones.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"single","title":"Tecnica","prompt":"Que tecnica corresponde?","options":[{"id":"a","label":"Combinaciones"},{"id":"b","label":"Permutaciones"}],"answer":"a","hint":"El orden no cambia la comision.","explanation":"Una comision sin cargos se cuenta con combinaciones."},{"kind":"numeric","title":"Calculo","prompt":"Calcula C(12,4).","answer":495,"tolerance":0,"hint":"(12*11*10*9)/(4*3*2*1).","explanation":"C(12,4)=495."}]'::jsonb, 200, true),
  ('est-c2-gs-021', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Permutaciones con cargos', 1, '<p>De 7 personas, cuantas formas hay de elegir presidente, vicepresidente y secretario?</p>', 'Los cargos son distintos.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"single","title":"Orden","prompt":"Importa el orden?","options":[{"id":"a","label":"Si"},{"id":"b","label":"No"}],"answer":"a","hint":"No es lo mismo ser presidente que secretario.","explanation":"Los cargos hacen que el orden importe."},{"kind":"numeric","title":"Calculo","prompt":"Calcula P(7,3).","answer":210,"tolerance":0,"hint":"7*6*5.","explanation":"P(7,3)=210."}]'::jsonb, 210, true),
  ('est-c2-gs-022', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Permutaciones con repeticion', 2, '<p>Cuantas formas distintas se pueden formar con las letras de la palabra MAMA?</p>', 'Hay letras repetidas.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"info","title":"Datos","content_html":"<p>La palabra tiene 4 letras. M se repite 2 veces y A se repite 2 veces.</p>"},{"kind":"formula","title":"Formula","prompt":"Escribe la formula de permutaciones con repeticion para MAMA.","accepted":["4!/(2!*2!)","4! / (2! * 2!)"],"hint":"Divide por los factoriales de las repeticiones.","explanation":"Se corrige el sobreconteo causado por letras repetidas."},{"kind":"numeric","title":"Resultado","prompt":"Calcula el numero de formas.","answer":6,"tolerance":0,"hint":"24/4.","explanation":"4!/(2!*2!)=6."}]'::jsonb, 220, true),
  ('est-c2-gs-023', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Al menos una defectuosa', 2, '<p>La probabilidad de que una pieza salga defectuosa es 0,15, y las piezas son independientes. Si se revisan 3, calcula P(al menos una defectuosa).</p>', 'Usa complemento: ninguna defectuosa.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"No defectuosa","prompt":"Cual es la probabilidad de que una pieza no sea defectuosa?","answer":0.85,"tolerance":0.001,"hint":"1 - 0,15.","explanation":"P(no defectuosa)=0,85."},{"kind":"numeric","title":"Ninguna defectuosa","prompt":"Calcula P(ninguna defectuosa en 3 piezas).","answer":0.614125,"tolerance":0.001,"hint":"0,85^3.","explanation":"0,85^3=0,614125."},{"kind":"numeric","title":"Al menos una","prompt":"Calcula P(al menos una defectuosa).","answer":0.385875,"tolerance":0.001,"hint":"1 - 0,614125.","explanation":"P=0,385875."}]'::jsonb, 230, true),
  ('est-c2-gs-024', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Tabla de accidentes', 2, '<p>En una empresa: Usa EPP: 12 accidentes y 108 no accidentes; No usa EPP: 28 accidentes y 52 no accidentes. Total 200 personas. Calcula P(accidente), P(accidente | no usa EPP) y P(usa EPP | accidente).</p>', 'En condicionales, cambia el denominador.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"P(accidente)","prompt":"Calcula P(accidente).","answer":0.2,"tolerance":0.001,"hint":"40/200.","explanation":"P(accidente)=40/200=0,20."},{"kind":"numeric","title":"P(accidente | no usa EPP)","prompt":"Calcula la probabilidad condicional.","answer":0.35,"tolerance":0.001,"hint":"28/80.","explanation":"Dentro de los que no usan EPP, 28 de 80 tuvieron accidente."},{"kind":"numeric","title":"P(usa EPP | accidente)","prompt":"Calcula la probabilidad condicional.","answer":0.3,"tolerance":0.001,"hint":"12/40.","explanation":"De los 40 accidentes, 12 ocurrieron usando EPP."}]'::jsonb, 240, true),
  ('est-c2-gs-025', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Interseccion desde union', 2, '<p>Si P(A)=0,6, P(B)=0,5 y P(A union B)=0,8, calcula P(A inter B).</p>', 'Despeja desde la formula de union.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"formula","title":"Despeje","prompt":"Escribe la formula despejada para P(A inter B).","accepted":["P(A inter B)=P(A)+P(B)-P(A union B)","P(A∩B)=P(A)+P(B)-P(A∪B)"],"hint":"La union suma y resta la interseccion.","explanation":"P(A inter B)=P(A)+P(B)-P(A union B)."},{"kind":"numeric","title":"Calculo","prompt":"Calcula P(A inter B).","answer":0.3,"tolerance":0.001,"hint":"0,6+0,5-0,8.","explanation":"P(A inter B)=0,3."}]'::jsonb, 250, true),
  ('est-c2-gs-026', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Condicional desde interseccion', 1, '<p>Si P(A inter B)=0,18 y P(B)=0,3, calcula P(A|B).</p>', 'Usa la definicion de probabilidad condicional.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"formula","title":"Formula","prompt":"Escribe la formula de P(A|B).","accepted":["P(A|B)=P(A inter B)/P(B)","P(A|B)=P(A∩B)/P(B)"],"hint":"La condicion B queda en el denominador.","explanation":"P(A|B)=P(A inter B)/P(B)."},{"kind":"numeric","title":"Calculo","prompt":"Calcula P(A|B).","answer":0.6,"tolerance":0.001,"hint":"0,18/0,3.","explanation":"P(A|B)=0,6."}]'::jsonb, 260, true),
  ('est-c2-gs-027', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'No suma 7', 1, '<p>Se lanzan dos dados. Calcula la probabilidad de que no salga suma 7.</p>', 'Usa complemento.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Suma 7","prompt":"Ingresa P(suma 7).","answer":0.166667,"tolerance":0.001,"hint":"6/36.","explanation":"P(suma 7)=6/36=1/6."},{"kind":"numeric","title":"Complemento","prompt":"Calcula P(no suma 7).","answer":0.833333,"tolerance":0.001,"hint":"1 - 1/6.","explanation":"P(no suma 7)=5/6=0,8333."}]'::jsonb, 270, true),
  ('est-c2-gs-028', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Figura o corazon en cartas', 2, '<p>Se saca una carta de una baraja de 52. Calcula la probabilidad de que sea figura o corazon.</p>', 'Es el mismo patron de union con interseccion.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Figuras","prompt":"Cuantas figuras hay?","answer":12,"tolerance":0,"hint":"J, Q, K por 4 pintas.","explanation":"Hay 12 figuras."},{"kind":"numeric","title":"Corazones","prompt":"Cuantos corazones hay?","answer":13,"tolerance":0,"hint":"Una pinta completa.","explanation":"Hay 13 corazones."},{"kind":"numeric","title":"Union","prompt":"Ingresa la probabilidad final como decimal.","answer":0.423077,"tolerance":0.001,"hint":"(12+13-3)/52.","explanation":"P=22/52=11/26=0,4231."}]'::jsonb, 280, true),
  ('est-c2-gs-029', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Condicional con estudio y aprobacion', 2, '<p>En una tabla: Estudia y aprueba 45, estudia y reprueba 15, no estudia y aprueba 20, no estudia y reprueba 20. Calcula P(aprueba | estudia) y P(estudia | aprueba).</p>', 'Cada condicional usa un denominador distinto.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"P(aprueba | estudia)","prompt":"Calcula P(aprueba | estudia).","answer":0.75,"tolerance":0.001,"hint":"45/60.","explanation":"De 60 que estudian, 45 aprueban."},{"kind":"numeric","title":"P(estudia | aprueba)","prompt":"Calcula P(estudia | aprueba).","answer":0.692308,"tolerance":0.001,"hint":"45/65.","explanation":"De 65 que aprueban, 45 estudian."},{"kind":"boolean","title":"Mismo resultado","prompt":"P(aprueba | estudia) siempre es igual a P(estudia | aprueba).","answer":false,"hint":"Mira los denominadores.","explanation":"Las condicionales invertidas no son equivalentes en general."}]'::jsonb, 290, true),
  ('est-c2-gs-030', 'estadistica-aplicada', 'estadistica-certamen2-probabilidad', 'guided_steps', 'Bolsa con tres colores', 3, '<p>Una caja tiene 4 bolas rojas, 3 azules y 2 verdes. Calcula P(no verde) para una extraccion y, si se extraen 2 sin reposicion, P(ambas de distinto color).</p>', 'Para distinto color, usa complemento: mismo color.', '', '[]'::jsonb, '[]'::jsonb, null, '', '', '[{"kind":"numeric","title":"Total","prompt":"Cuantas bolas hay en total?","answer":9,"tolerance":0,"hint":"4+3+2.","explanation":"Hay 9 bolas."},{"kind":"numeric","title":"No verde","prompt":"Calcula P(no verde).","answer":0.777778,"tolerance":0.001,"hint":"7/9.","explanation":"No verde significa roja o azul: 7/9."},{"kind":"numeric","title":"Mismo color","prompt":"Calcula P(mismo color) para dos extracciones sin reposicion.","answer":0.277778,"tolerance":0.001,"hint":"Rojas: 12/72, azules: 6/72, verdes: 2/72.","explanation":"P(mismo color)=20/72=5/18."},{"kind":"numeric","title":"Distinto color","prompt":"Calcula P(distinto color).","answer":0.722222,"tolerance":0.001,"hint":"1 - 5/18.","explanation":"P(distinto color)=13/18=0,7222."}]'::jsonb, 300, true)
on conflict (id) do update set
  course_id = excluded.course_id,
  module_id = excluded.module_id,
  type = excluded.type,
  title = excluded.title,
  level = excluded.level,
  statement_html = excluded.statement_html,
  hint = excluded.hint,
  starter = excluded.starter,
  tests = excluded.tests,
  options = excluded.options,
  correct_answer = excluded.correct_answer,
  explanation = excluded.explanation,
  solution_html = excluded.solution_html,
  steps = excluded.steps,
  sort_order = excluded.sort_order,
  is_published = excluded.is_published;

